{% set name = "resvg" %}
{% set version = "0.36.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RazrFalcon/resvg/archive/v{{ version }}.tar.gz
  sha256: 193cb27744c223579eee5f227549be8c53c3e31270d2c85522987dbf3bec3869

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses

test:
  commands:
    - resvg --help
    - resvg --version

about:
  home: https://github.com/RazrFalcon/resvg
  license: MPL-2.0
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: An SVG rendering library.

extra:
  recipe-maintainers:
    - maresb
